### ISSUE TITLE
Unipi 1.1: no 1-wire sensors will read values when one sensors is missing

### ISSUE THREAD

**Issue by onosek** [UniPiTechnology/evok#101]
### Prerequisites

* Raspberry Pi4 4GB
* previous evok version 2.3.6
* upgraded to 2.4.24 by "legacy installation process"

### evok.conf snippet

[OWBUS_1]
owbus = /dev/i2c-1 ; Mandatory, scanned bus (--i2c=/dev/i2c-1:ALL or localhost:2122 or 'u' for USB dongle)
interval = 3          					; Mandatory, [s] length of sensor reading
scan_interval = 300    					; Mandatory, [s] How often the scanning is done

[SENSOR_1]	     						; onewire thermometer
bus = 1		     					; link to OWBUS_1
address = 28094E94970E03
type = DS18B20
interval = 10
alias = bojler

[SENSOR_2]	     						; onewire thermometer
;bus = 1		     					; link to OWBUS_1
;address = 28E90B94970C03
;type = DS18B20
;interval = 10
;alias = chodba

### Description

I had two sensors (Dallas thermometers; connected with 3 wires; no more than 5m long) defined in the evok configuration. One of them (SENSOR_2) wasn't connected. Worked well.
After the upgrade, my configuration had to be changed - the sensor's addresses are now 2 characters shorter. Right?
But after the evok restart, the connected thermometer loaded its value just once. it (http://<IP>:8080/json/sensor/1). Neither value nor timestamp refreshes after 10 seconds.
The currently unused (SENSOR_2) sensor's configuration had to be commented out. SENSOR_1 started working again.
I think that situation, when one of the sensors is damaged/removed/stolen/... and others stop working is not good.

**Expected behavior:** [What you expected to happen]
The physically missing sensor won't affect reading from others.

Thanks for your efforts with this good piece of software.
ON

**Comment by kratochvil01** [comment]
Solved in Evok v3.0.1

**Comment by onosek** [comment]
Thanks.
