### ISSUE TITLE
[GENERAL] Add possibility to set multiple outputs at the same time

### ISSUE THREAD

**Issue by tomashora** [UniPiTechnology/evok#11]
Eg from websocket

**Comment by capitanfindus** [comment]
Hi, any news about this issue?
Is this valid at line 229?

https://github.com/kimmoli/evok/blob/master/evok/evok.py

**Comment by tomashora** [comment]
This is valid only for the UniPi 1

**Comment by tknot** [comment]
In the release candidate 2.0a the Bulk API allows for sending any number and variety of commands at once
