### ISSUE TITLE
If ds_mode is set to any other mode than SIMPLE, it cannot be changed

### ISSUE THREAD

**Issue by vytun** [UniPiTechnology/evok#121]
If **ds_mode** is set to any other mode than SIMPLE, it cannot be changed or DS can be turned off completely.  Tested on Extension and controller.

After saving the configuration and power cycle the controller and Extension, it still cannot be changed – Q.E.D.

**Comment by kratochvil01** [comment]
Fixed [here](https://github.com/UniPiTechnology/evok/commit/3d543dc4b8b4b92ff1843078b2ad1c38022b252f).
