### ISSUE TITLE
Behaviour when some Modbus device(s) fail

### ISSUE THREAD

**Issue by vytun** [UniPiTechnology/evok#123]
If not all devices communicate (one or more devices fail), some writes, e.g. RO, will fail. In some cases it happened that after some time (about 10s after 3 out of 6 devices disconnected) even MWD was triggered (set to 2.5s on Extension xS11). 
The problem is probably due to the fact that the slowdown is applied to individual communication group, not to all device groups when the timeout first occurs for any group of this device.

Possible solution: if a timeout occurs for one group, slow down all groups of that device.

**Comment by kratochvil01** [comment]
I fix this [here](https://github.com/UniPiTechnology/evok/commit/b3830b7ba9619651811903b505d1d943d98df4d3).

If a timeout now occurs when reading a modbus registry group. Evok will slow down all groups of that device.
