### ISSUE TITLE
Invalid device circuit number 1_01

### ISSUE THREAD

**Issue by GlennGeenen** [UniPiTechnology/evok#130]
### Prerequisites

* [x] Are you running the latest Master or the latest release version?
* [x] Did you try to reinstall EVOK?
* [x] Did you perform a cursory search on the [forum] and [google]?

### Log files needed

```
[I 240401 08:22:38 config:78] eprom: UniPi Neuron L203 version: 1.4 serial: 0x59
[I 240401 08:22:38 evok:1899] Starting using config file /etc/evok.conf
[I 240401 08:22:38 config:110] YAML Definition loaded: /etc/hw_definitions/BuiltIn/L203.yaml, type: UniPiBuiltIn
[I 240401 08:22:39 config:103] YAML Definition loaded: xS40.yaml, type: 3, definition count 0
[I 240401 08:22:39 config:103] YAML Definition loaded: IC-Di1Ro2-1.yaml, type: 3, definition count 1
[I 240401 08:22:39 config:103] YAML Definition loaded: IC-Light1P-1.yaml, type: 3, definition count 2
[I 240401 08:22:39 config:103] YAML Definition loaded: xS11.yaml, type: 3, definition count 3
[I 240401 08:22:39 config:103] YAML Definition loaded: ID-AiUC8-1.yaml, type: 3, definition count 4
[I 240401 08:22:39 config:103] YAML Definition loaded: IAQ.yaml, type: 3, definition count 5
[I 240401 08:22:39 config:103] YAML Definition loaded: xS30.yaml, type: 3, definition count 6
[I 240401 08:22:39 config:103] YAML Definition loaded: xG18.yaml, type: 3, definition count 7
[I 240401 08:22:39 config:103] YAML Definition loaded: ID-Do16-1.yaml, type: 3, definition count 8
[I 240401 08:22:39 config:103] YAML Definition loaded: xS10.yaml, type: 3, definition count 9
[I 240401 08:22:39 config:103] YAML Definition loaded: IC-DiS2Do2-1.yaml, type: 3, definition count 10
[I 240401 08:22:39 config:103] YAML Definition loaded: xS50.yaml, type: 3, definition count 11
[I 240401 08:22:39 config:103] YAML Definition loaded: CUSTOM_MODBUS_DEVICE.yaml, type: 3, definition count 12
[I 240401 08:22:39 config:103] YAML Definition loaded: ID-DiS16-1.yaml, type: 3, definition count 13
[I 240401 08:22:39 config:103] YAML Definition loaded: IC-AiUC8-2.yaml, type: 3, definition count 14
[I 240401 08:22:39 config:103] YAML Definition loaded: xS51.yaml, type: 3, definition count 15
[I 240401 08:22:39 config:103] YAML Definition loaded: evok-alias.yaml, type: 2, definition count 0
[I 240401 08:22:39 evok:1969] HTTP server listening on port: 8080
[I 240401 08:22:39 modbusclient_tornado:134] TCP/Modbus client to 127.0.0.1:502 started
[I 240401 08:22:39 neuron:215] Reading SPI boards
[I 240401 08:22:39 neuron:230] No board on SPI 1
[I 240401 08:22:39 neuron:230] No board on SPI 2
[I 240401 08:22:39 neuron:230] No board on SPI 3
[E 240401 08:22:39 config:421] Invalid device circuit number 1_01
    Traceback (most recent call last):
      File "/opt/evok/lib/python2.7/site-packages/evok/config.py", line 416, in add_aliases
        dev_obj = Devices.by_int(dev_pointer["dev_type"], dev_pointer["circuit"])
      File "/opt/evok/lib/python2.7/site-packages/evok/devices.py", line 68, in by_int
        raise Exception('Invalid device circuit number %s' % str(circuit))
    Exception: Invalid device circuit number 1_01
[E 240401 08:22:39 config:421] Invalid device circuit number 1_02
    Traceback (most recent call last):
      File "/opt/evok/lib/python2.7/site-packages/evok/config.py", line 416, in add_aliases
        dev_obj = Devices.by_int(dev_pointer["dev_type"], dev_pointer["circuit"])
      File "/opt/evok/lib/python2.7/site-packages/evok/devices.py", line 68, in by_int
        raise Exception('Invalid device circuit number %s' % str(circuit))
    Exception: Invalid device circuit number 1_02
[I 240401 08:22:39 owclient:450] Entering OWW loop with PID 703

```

```
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    3 ?        I<     0:00  \_ [rcu_gp]
    4 ?        I<     0:00  \_ [rcu_par_gp]
    6 ?        I<     0:00  \_ [kworker/0:0H-mmc_complete]
    8 ?        I<     0:00  \_ [mm_percpu_wq]
    9 ?        S      0:00  \_ [rcu_tasks_rude_]
   10 ?        S      0:00  \_ [rcu_tasks_trace]
   11 ?        S      0:00  \_ [ksoftirqd/0]
   12 ?        I      0:00  \_ [rcu_sched]
   13 ?        S      0:00  \_ [migration/0]
   14 ?        S      0:00  \_ [cpuhp/0]
   15 ?        S      0:00  \_ [cpuhp/1]
   16 ?        S      0:00  \_ [migration/1]
   17 ?        S      0:00  \_ [ksoftirqd/1]
   20 ?        S      0:00  \_ [cpuhp/2]
   21 ?        S      0:00  \_ [migration/2]
   22 ?        S      0:00  \_ [ksoftirqd/2]
   25 ?        S      0:00  \_ [cpuhp/3]
   26 ?        S      0:00  \_ [migration/3]
   27 ?        S      0:00  \_ [ksoftirqd/3]
   30 ?        S      0:00  \_ [kdevtmpfs]
   31 ?        I<     0:00  \_ [netns]
   34 ?        S      0:00  \_ [kauditd]
   36 ?        S      0:00  \_ [khungtaskd]
   37 ?        S      0:00  \_ [oom_reaper]
   38 ?        I<     0:00  \_ [writeback]
   39 ?        S      0:00  \_ [kcompactd0]
   59 ?        I<     0:00  \_ [kblockd]
   60 ?        I<     0:00  \_ [blkcg_punt_bio]
   61 ?        S      0:00  \_ [watchdogd]
   63 ?        I<     0:00  \_ [rpciod]
   64 ?        I<     0:00  \_ [kworker/u9:0]
   65 ?        I<     0:00  \_ [xprtiod]
   68 ?        S      0:00  \_ [kswapd0]
   69 ?        I<     0:00  \_ [nfsiod]
   70 ?        I<     0:00  \_ [kthrotld]
   71 ?        I<     0:00  \_ [iscsi_eh]
   72 ?        I<     0:00  \_ [iscsi_destroy]
   73 ?        I<     0:00  \_ [nvme-wq]
   74 ?        I<     0:00  \_ [nvme-reset-wq]
   75 ?        I<     0:00  \_ [nvme-delete-wq]
   76 ?        I      0:00  \_ [kworker/u8:1-events_unbound]
   78 ?        I<     0:00  \_ [DWC Notificatio]
   79 ?        I<     0:00  \_ [uas]
   80 ?        S<     0:00  \_ [vchiq-slot/0]
   81 ?        S<     0:00  \_ [vchiq-recy/0]
   82 ?        S<     0:00  \_ [vchiq-sync/0]
   83 ?        I<     0:00  \_ [zswap-shrink]
   87 ?        I<     0:00  \_ [sdhci]
   88 ?        S      0:00  \_ [irq/49-mmc0]
   89 ?        I      0:00  \_ [kworker/0:6-events_freezable]
  106 ?        I<     0:00  \_ [mmc_complete]
  128 ?        I<     0:00  \_ [kworker/0:2H-mmc_complete]
  134 ?        I      0:00  \_ [kworker/2:2-events_power_efficient]
  137 ?        I<     0:00  \_ [kworker/2:1H-kblockd]
  145 ?        I<     0:00  \_ [kworker/2:2H]
  157 ?        I      0:00  \_ [kworker/u8:2-events_unbound]
  175 ?        I<     0:00  \_ [kworker/1:1H-kblockd]
  179 ?        S      0:00  \_ [jbd2/mmcblk0p2-]
  180 ?        I<     0:00  \_ [ext4-rsv-conver]
  188 ?        I      0:00  \_ [kworker/3:2-mm_percpu_wq]
  199 ?        I<     0:00  \_ [ipv6_addrconf]
  235 ?        I<     0:00  \_ [kworker/3:2H-kblockd]
  284 ?        S      0:00  \_ [spi0]
  285 ?        I      0:00  \_ [kworker/2:3-events]
  304 ?        I<     0:00  \_ [cfg80211]
  308 ?        I<     0:00  \_ [brcmf_wq/mmc1:0]
  311 ?        S      0:00  \_ [brcmf_wdog/mmc1]
  319 ?        S      0:00  \_ [vchiq-keep/0]
  320 ?        S<     0:00  \_ [SMIO]
  325 ?        I<     0:00  \_ [mmal-vchiq]
  332 ?        S      0:00  \_ [v3d_bin]
  334 ?        S      0:00  \_ [v3d_render]
  335 ?        S      0:00  \_ [v3d_tfu]
  337 ?        S      0:00  \_ [v3d_csd]
  338 ?        S      0:00  \_ [v3d_cache_clean]
  382 ?        D      0:00  \_ [unipispi_inv]
  424 ?        I      0:00  \_ [kworker/1:2-mm_percpu_wq]
  604 ?        I      0:00  \_ [kworker/3:0-mm_percpu_wq]
  605 ?        I      0:00  \_ [kworker/1:0-mm_percpu_wq]
  624 ?        I<     0:00  \_ [kworker/3:0H-kblockd]
  625 ?        I      0:00  \_ [kworker/0:0-mm_percpu_wq]
  626 ?        I<     0:00  \_ [kworker/1:0H]
  641 ?        I      0:00  \_ [kworker/3:1-events]
  642 ?        I      0:00  \_ [kworker/1:1-events_power_efficient]
  657 ?        I<     0:00  \_ [kworker/2:0H]
  658 ?        I<     0:00  \_ [kworker/0:1H]
  680 ?        I      0:00  \_ [kworker/2:0-events]
  681 ?        I      0:00  \_ [kworker/u8:0]
  705 ?        I      0:00  \_ [kworker/0:1]
    1 ?        Ss     0:04 /sbin/init
  224 ?        Ss     0:00 /lib/systemd/systemd-journald
  245 ?        Ss     0:00 /lib/systemd/systemd-udevd
  419 ?        Ssl    0:00 /lib/systemd/systemd-timesyncd
  423 ?        Ss     0:03 /usr/sbin/haveged --Foreground --verbose=1 -w 1024
  460 ?        Ss     0:00 /usr/sbin/cron -f
  462 ?        Ss     0:00 /lib/systemd/systemd-logind
  465 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  467 ?        Ss     0:00 /sbin/dhcpcd -q -b
  469 ?        Ss     0:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
  470 ?        SNsl   0:11 node-red
  489 ?        Ss     0:00 avahi-daemon: running [L203-sn89.local]
  493 ?        S      0:00  \_ avahi-daemon: chroot helper
  490 ?        Ss     0:00 /opt/unipi/tools/unipi_tcp_server -l 127.0.0.1 -p 502
  495 tty1     Ss+    0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
  510 ?        Ss     0:00 /usr/sbin/sshd -D
  580 ?        Ss     0:00  \_ sshd: unipi [priv]
  597 ?        S      0:00      \_ sshd: unipi@pts/0
  598 pts/0    Ss     0:00          \_ -bash
  682 pts/0    S      0:00              \_ sudo su
  683 pts/0    S      0:00                  \_ su
  684 pts/0    S      0:00                      \_ bash
  685 pts/0    S      0:00                          \_ sudo su
  686 pts/0    S      0:00                              \_ su
  687 pts/0    S      0:00                                  \_ bash
  715 pts/0    R+     0:00                                      \_ ps -fax
  583 ?        Ss     0:00 /lib/systemd/systemd --user
  584 ?        S      0:00  \_ (sd-pam)
  697 ?        Ss     0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
  698 ?        S      0:00  \_ nginx: worker process
  699 ?        S      0:00  \_ nginx: worker process
  700 ?        S      0:00  \_ nginx: worker process
  701 ?        S      0:00  \_ nginx: worker process
  712 ?        Ss     0:02 /opt/evok/bin/python /opt/evok/lib/python2.7/site-packages/evok/evok.py
  713 ?        Sl     0:00  \_ /opt/evok/bin/python /opt/evok/lib/python2.7/site-packages/evok/evok.py

```

### Description

Inputs/Outputs dashboard empty. Error in the logs when I interact with NodeRed:
```
[E 240401 08:22:39 config:421] Invalid device circuit number 1_02
    Traceback (most recent call last):
      File "/opt/evok/lib/python2.7/site-packages/evok/config.py", line 416, in add_aliases
        dev_obj = Devices.by_int(dev_pointer["dev_type"], dev_pointer["circuit"])
      File "/opt/evok/lib/python2.7/site-packages/evok/devices.py", line 68, in by_int
        raise Exception('Invalid device circuit number %s' % str(circuit))
    Exception: Invalid device circuit number 1_02
```

### Steps to Reproduce

1. Installed latest Node-RED image: https://kb.unipi.technology/en:hw:02-neuron:download-image:02-nodered on a RPi4 on Neuron L203
2. Updated to latest evok version which makes no difference (https://evok.readthedocs.io/en/latest/installation/)

[forum]:https://forum.unipi.technology/category/4/official-evok-api
[google]:http://www.google.com/

**Comment by miroslav-ondra** [comment]
Can you send us output of dmesg? Important section about spi /unipi devices.

**Comment by GlennGeenen** [comment]
i disabled the wifi so the brcmfmac errors disappeared. No red lines, only a bold message:
**Kernel parameter elevator= does not have any effect anymore.
Please use sysfs to set IO scheduler for individual devices.**

**Comment by kratochvil01** [comment]
Hello
It looks like Hardware problem. The device cannot establish a connection with any section. Did this device work with another OS?

You can try [beta version](https://evok.readthedocs.io/en/latest/installation/#node-red-beta-os-images) with newer drivers.

**Comment by GlennGeenen** [comment]
beta version shows errors on boot:
[    5.906682] unipi-spi spi0.3: spi channel looks empty
[    5.910061] unipi-spi spi0.2: spi channel looks empty
[    5.910789] unipi-spi spi0.1: spi channel looks empty

evok log:
INFO:evok:Starting Evok v3.0.1 using config directory '/etc/evok'.
INFO:evok:Setting logging level to 'DEBUG'.
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/13.yaml, definition count 0
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/00.yaml, definition count 1
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS50.yaml, definition count 2
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xG18.yaml, definition count 3
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/07.yaml, definition count 4
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/08.yaml, definition count 5
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS40.yaml, definition count 6
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/IAQ-TH.yaml, definition count 7
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/IAQ-THC.yaml, definition count 8
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/01.yaml, definition count 9
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/CUSTOM_MODBUS_DEVICE.yaml, definition count 10
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS51.yaml, definition count 11
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/0A.yaml, definition count 12
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS11.yaml, definition count 13
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS10.yaml, definition count 14
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/09.yaml, definition count 15
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/0F.yaml, definition count 16
DEBUG:evok:YAML Definition loaded: /etc/evok/hw_definitions/xS30.yaml, definition count 17
DEBUG:evok:Load aliases with {}
INFO:evok:HTTP server API listening on 127.0.0.1:8080
DEBUG:evok:Registered new device 'tcp_bus' with circuit LOCAL_TCP 	 (<evok.config.TcpBusDevice object at 0xb5c781f0>)
DEBUG:evok:Registered new device 'device_info' with circuit Neuron_L203_89 	 (<evok.config.DeviceInfo object at 0xb5c78e50>)
INFO:evok:Creating bus 'LOCAL_TCP' with type 'MODBUSTCP' with devices.
INFO:evok:^ Creating device '1' with type 'MODBUSTCP'
DEBUG:evok:Registered new device 'modbus_slave' with circuit 1 	 (<evok.modbus_slave.ModbusSlave object at 0xb5c78750>)
INFO:evok:^ Creating device '2' with type 'MODBUSTCP'
DEBUG:evok:Registered new device 'modbus_slave' with circuit 2 	 (<evok.modbus_slave.ModbusSlave object at 0xb5c78cf0>)
INFO:evok:^ Creating device '3' with type 'MODBUSTCP'
DEBUG:evok:Registered new device 'modbus_slave' with circuit 3 	 (<evok.modbus_slave.ModbusSlave object at 0xb5c879f0>)
DEBUG:evok:Registered new device 'run' with circuit alias 	 (<evok.devices.Aliases object at 0xb5cb6c90>)
INFO:evok:Initial reading the Modbus board on Modbus address 1	(1)
INFO:evok:Initial reading the Modbus board on Modbus address 2	(2)
INFO:evok:Initial reading the Modbus board on Modbus address 3	(3)
DEBUG:evok:Registered new device 'input' with circuit 2_01 	 (<evok.modbus_slave.Input object at 0xb5c87090>)
DEBUG:evok:Registered new device 'input' with circuit 2_02 	 (<evok.modbus_slave.Input object at 0xb5c87d10>)
DEBUG:evok:Registered new device 'input' with circuit 2_03 	 (<evok.modbus_slave.Input object at 0xb5c87f10>)
DEBUG:evok:Registered new device 'input' with circuit 2_04 	 (<evok.modbus_slave.Input object at 0xb5c87970>)
DEBUG:evok:Registered new device 'input' with circuit 2_05 	 (<evok.modbus_slave.Input object at 0xb5c76a10>)
DEBUG:evok:Registered new device 'input' with circuit 2_06 	 (<evok.modbus_slave.Input object at 0xb5c768d0>)
DEBUG:evok:Registered new device 'input' with circuit 2_07 	 (<evok.modbus_slave.Input object at 0xb5c76ab0>)
DEBUG:evok:Registered new device 'input' with circuit 2_08 	 (<evok.modbus_slave.Input object at 0xb5c76c50>)
DEBUG:evok:Registered new device 'input' with circuit 2_09 	 (<evok.modbus_slave.Input object at 0xb5c76c70>)
DEBUG:evok:Registered new device 'input' with circuit 2_10 	 (<evok.modbus_slave.Input object at 0xb5c76cd0>)
DEBUG:evok:Registered new device 'input' with circuit 2_11 	 (<evok.modbus_slave.Input object at 0xb5c76a90>)
DEBUG:evok:Registered new device 'input' with circuit 2_12 	 (<evok.modbus_slave.Input object at 0xb5c76670>)
DEBUG:evok:Registered new device 'input' with circuit 2_13 	 (<evok.modbus_slave.Input object at 0xb5c76a70>)
DEBUG:evok:Registered new device 'input' with circuit 2_14 	 (<evok.modbus_slave.Input object at 0xb5c76130>)
DEBUG:evok:Registered new device 'input' with circuit 2_15 	 (<evok.modbus_slave.Input object at 0xb5c767f0>)
DEBUG:evok:Registered new device 'input' with circuit 2_16 	 (<evok.modbus_slave.Input object at 0xb5c76570>)
DEBUG:evok:Registered new device 'relay' with circuit 2_01 	 (<evok.modbus_slave.Relay object at 0xb5c76bb0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_02 	 (<evok.modbus_slave.Relay object at 0xb5c76eb0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_03 	 (<evok.modbus_slave.Relay object at 0xb5c759d0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_04 	 (<evok.modbus_slave.Relay object at 0xb5c75b50>)
DEBUG:evok:Registered new device 'relay' with circuit 2_05 	 (<evok.modbus_slave.Relay object at 0xb5c752d0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_06 	 (<evok.modbus_slave.Relay object at 0xb5c753f0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_07 	 (<evok.modbus_slave.Relay object at 0xb5c75410>)
DEBUG:evok:Registered new device 'relay' with circuit 2_08 	 (<evok.modbus_slave.Relay object at 0xb5c75c70>)
DEBUG:evok:Registered new device 'relay' with circuit 2_09 	 (<evok.modbus_slave.Relay object at 0xb5c752b0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_10 	 (<evok.modbus_slave.Relay object at 0xb5c75a70>)
DEBUG:evok:Registered new device 'relay' with circuit 2_11 	 (<evok.modbus_slave.Relay object at 0xb5c75db0>)
DEBUG:evok:Registered new device 'relay' with circuit 2_12 	 (<evok.modbus_slave.Relay object at 0xb5c75730>)
DEBUG:evok:Registered new device 'relay' with circuit 2_13 	 (<evok.modbus_slave.Relay object at 0xb5c75190>)
DEBUG:evok:Registered new device 'relay' with circuit 2_14 	 (<evok.modbus_slave.Relay object at 0xb5c754d0>)
DEBUG:evok:Registered new device 'watchdog' with circuit 2_01 	 (<evok.modbus_slave.Watchdog object at 0xb5c753b0>)
DEBUG:evok:Registered new device 'input' with circuit 3_01 	 (<evok.modbus_slave.Input object at 0xb5c87e50>)
DEBUG:evok:Registered new device 'input' with circuit 3_02 	 (<evok.modbus_slave.Input object at 0xb5c75590>)
DEBUG:evok:Registered new device 'input' with circuit 3_03 	 (<evok.modbus_slave.Input object at 0xb5c75030>)
DEBUG:evok:Registered new device 'input' with circuit 3_04 	 (<evok.modbus_slave.Input object at 0xb5c75e70>)
DEBUG:evok:Registered new device 'input' with circuit 3_05 	 (<evok.modbus_slave.Input object at 0xb5c75b70>)
DEBUG:evok:Registered new device 'input' with circuit 3_06 	 (<evok.modbus_slave.Input object at 0xb5c807f0>)
DEBUG:evok:Registered new device 'input' with circuit 3_07 	 (<evok.modbus_slave.Input object at 0xb5c80730>)
DEBUG:evok:Registered new device 'input' with circuit 3_08 	 (<evok.modbus_slave.Input object at 0xb5c80db0>)
DEBUG:evok:Registered new device 'input' with circuit 3_09 	 (<evok.modbus_slave.Input object at 0xb5c80070>)
DEBUG:evok:Registered new device 'input' with circuit 3_10 	 (<evok.modbus_slave.Input object at 0xb5c80fd0>)
DEBUG:evok:Registered new device 'input' with circuit 3_11 	 (<evok.modbus_slave.Input object at 0xb5c80110>)
DEBUG:evok:Registered new device 'input' with circuit 3_12 	 (<evok.modbus_slave.Input object at 0xb5c80ed0>)
DEBUG:evok:Registered new device 'input' with circuit 3_13 	 (<evok.modbus_slave.Input object at 0xb5c80f10>)
DEBUG:evok:Registered new device 'input' with circuit 3_14 	 (<evok.modbus_slave.Input object at 0xb5c801b0>)
DEBUG:evok:Registered new device 'input' with circuit 3_15 	 (<evok.modbus_slave.Input object at 0xb5c80cd0>)
DEBUG:evok:Registered new device 'input' with circuit 3_16 	 (<evok.modbus_slave.Input object at 0xb5c807b0>)
DEBUG:evok:Registered new device 'relay' with circuit 3_01 	 (<evok.modbus_slave.Relay object at 0xb5c80330>)
DEBUG:evok:Registered new device 'relay' with circuit 3_02 	 (<evok.modbus_slave.Relay object at 0xb5c80a70>)
DEBUG:evok:Registered new device 'relay' with circuit 3_03 	 (<evok.modbus_slave.Relay object at 0xb5c80f90>)
DEBUG:evok:Registered new device 'relay' with circuit 3_04 	 (<evok.modbus_slave.Relay object at 0xb5c802f0>)
DEBUG:evok:Registered new device 'relay' with circuit 3_05 	 (<evok.modbus_slave.Relay object at 0xb5c80650>)
DEBUG:evok:Registered new device 'relay' with circuit 3_06 	 (<evok.modbus_slave.Relay object at 0xb5c80210>)
DEBUG:evok:Registered new device 'relay' with circuit 3_07 	 (<evok.modbus_slave.Relay object at 0xb5c85690>)
DEBUG:evok:Registered new device 'relay' with circuit 3_08 	 (<evok.modbus_slave.Relay object at 0xb5c85030>)
DEBUG:evok:Registered new device 'relay' with circuit 3_09 	 (<evok.modbus_slave.Relay object at 0xb5c857d0>)
DEBUG:evok:Registered new device 'relay' with circuit 3_10 	 (<evok.modbus_slave.Relay object at 0xb5c852f0>)
DEBUG:evok:Registered new device 'relay' with circuit 3_11 	 (<evok.modbus_slave.Relay object at 0xb5c85550>)
DEBUG:evok:Registered new device 'relay' with circuit 3_12 	 (<evok.modbus_slave.Relay object at 0xb5c85e50>)
DEBUG:evok:Registered new device 'relay' with circuit 3_13 	 (<evok.modbus_slave.Relay object at 0xb5c85210>)
DEBUG:evok:Registered new device 'relay' with circuit 3_14 	 (<evok.modbus_slave.Relay object at 0xb5c85af0>)
DEBUG:evok:Registered new device 'watchdog' with circuit 3_01 	 (<evok.modbus_slave.Watchdog object at 0xb5c85270>)
DEBUG:evok:Registered new device 'input' with circuit 1_01 	 (<evok.modbus_slave.Input object at 0xb5c87930>)
DEBUG:evok:Registered new device 'input' with circuit 1_02 	 (<evok.modbus_slave.Input object at 0xb5c87890>)
DEBUG:evok:Registered new device 'input' with circuit 1_03 	 (<evok.modbus_slave.Input object at 0xb5c76b70>)
DEBUG:evok:Registered new device 'input' with circuit 1_04 	 (<evok.modbus_slave.Input object at 0xb5c85470>)
DEBUG:evok:Registered new device 'output' with circuit 1_01 	 (<evok.modbus_slave.Output object at 0xb5c853d0>)
DEBUG:evok:Registered new device 'output' with circuit 1_02 	 (<evok.modbus_slave.Output object at 0xb5c85a50>)
DEBUG:evok:Registered new device 'output' with circuit 1_03 	 (<evok.modbus_slave.Output object at 0xb5c85eb0>)
DEBUG:evok:Registered new device 'output' with circuit 1_04 	 (<evok.modbus_slave.Output object at 0xb5c85e90>)
DEBUG:evok:Registered new device 'ai' with circuit 1_01 	 (<evok.modbus_slave.AnalogInput object at 0xb5c85f50>)
DEBUG:evok:Registered new device 'ao' with circuit 1_01 	 (<evok.modbus_slave.AnalogOutputBrain object at 0xb5c85ef0>)
DEBUG:evok:Registered new device 'led' with circuit 1_01 	 (<evok.modbus_slave.ULED object at 0xb5c851d0>)
DEBUG:evok:Registered new device 'led' with circuit 1_02 	 (<evok.modbus_slave.ULED object at 0xb5c85f30>)
DEBUG:evok:Registered new device 'led' with circuit 1_03 	 (<evok.modbus_slave.ULED object at 0xb5c85f90>)
DEBUG:evok:Registered new device 'led' with circuit 1_04 	 (<evok.modbus_slave.ULED object at 0xb5c85710>)
DEBUG:evok:Registered new device 'owpower' with circuit 1 	 (<evok.modbus_slave.OwPower object at 0xb5c85d50>)
DEBUG:evok:Registered new device 'watchdog' with circuit 1_01 	 (<evok.modbus_slave.Watchdog object at 0xb5c85a30>)
DEBUG:evok:New WebSocket client connected
ERROR:evok:3: Error while scanning: 'NoneType' object has no attribute 'done'
Traceback (most recent call last):
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_slave.py", line 220, in scan_boards
    if await self.modbus_cache_map.do_scan(slave=self.modbus_address) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_slave.py", line 98, in do_scan
    vals = await self.modbus_slave.client.read_holding_registers(m_reg_group['start_reg'], m_reg_group['count'], slave=slave)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_unipi.py", line 57, in ret
    return await operation(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/client/base.py", line 206, in async_execute
    self.close(reconnect=True)
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/client/base.py", line 153, in close
    self.connection_lost(asyncio.TimeoutError("Server not responding"))
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/transport/transport.py", line 307, in connection_lost
    self.callback_disconnected(reason)
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/client/base.py", line 224, in callback_disconnected
    self.raise_future(
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/client/base.py", line 234, in raise_future
    if not my_future.done():
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'done'
WARNING:evok:Slowing down device: '3'
ERROR:evok:2: Error while scanning: Modbus Error: [Connection] Connection lost during request
Traceback (most recent call last):
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_slave.py", line 220, in scan_boards
    if await self.modbus_cache_map.do_scan(slave=self.modbus_address) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_slave.py", line 98, in do_scan
    vals = await self.modbus_slave.client.read_holding_registers(m_reg_group['start_reg'], m_reg_group['count'], slave=slave)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/evok/modbus_unipi.py", line 57, in ret
    return await operation(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/evok/lib/python3.11/site-packages/pymodbus/client/base.py", line 199, in async_execute
    resp = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request
WARNING:evok:Slowing down device: '2'

**Comment by kratochvil01** [comment]
[11:50] Antonín Všetula
Our service department determined that the SPI bus fault was caused by the use of non-original DIN holder mounting screws. The fault was not destructive, the controller is now working properly.
 heart 1
