### ISSUE TITLE
[Feature]: Refactor I/O naming

### ISSUE THREAD

**Issue by tomashora** [UniPiTechnology/evok#157]
### Describe the feature

Refactor naming of I/Os to di,do,ai,ao,ro (which should be used primarly). Obsolete /input and /output endpoints could be preserved as aliases if it brings 100% backward compatibility (so users won't have to change their app at all).

Most work will have to be done in the documentation and javascript of evok-web.

Make sure to cleanup the devtype_names and aliases in devices.py from unsupported/obsolete devices.

### Use case

Access to I/Os will match naming conventions on the products however, it will break userapplications using these API calls

**Comment by kratochvil01** [comment]
Changes must be refrected in:

- [ ] evok-web.
- [ ] documentation.
- [ ] API documentation. 
- [ ] node-red nodes

**Comment by kratochvil01** [comment]
https://github.com/UniPiTechnology/evok/pull/158
