### ISSUE TITLE
[Bug]: No web interface

### ISSUE THREAD

**Issue by domguard** [UniPiTechnology/evok#159]
### Prerequisites

- [X] I am running the latest Evok version
- [X] I have searched other [issues](https://github.com/UniPiTechnology/evok/issues)

### Describe the bug

I had to re-install a working Neuron with node-red install. Due to many other problems, I finally end up installing the Node-Red OS Image, beta version.
To setup again my 1W sensors, i discovered there's no more web interface for EVOK : I used it to copy/paste the 1W sensors IDs, and also to check relays state when debugging : this neuron drives a plants dryer which is 100 meters from home.

Evok conf file talks about Nginx but it's missing in the install or has been replaced by Tornado ?
I commented out the "address" parameter in evok.conf to access it from th"e local network, but I only get a 404 on the http root url
and a never-ending request on the https side.

### Evok log

May 14 16:21:16 L203-sn123 systemd[1]: Started evok.service - EVOK Rest/WebSocket/RPC Server.
May 14 16:21:20 L203-sn123 evok[2320]: INFO:evok:Starting Evok v3.0.1 using config directory '/etc/evok'.
May 14 16:21:20 L203-sn123 evok[2320]: INFO:evok:Setting logging level to 'WARNING'.
May 14 16:21:39 L203-sn123 evok[2320]: WARNING:tornado.access:404 GET / (192.168.1.100) 2.19ms
May 14 16:21:39 L203-sn123 evok[2320]: WARNING:tornado.access:404 GET /favicon.ico (192.168.1.100) 1.99ms
May 14 16:21:59 L203-sn123 evok[2320]: WARNING:tornado.access:404 GET / (192.168.1.100) 1.75ms
May 14 16:31:39 L203-sn123 evok[2320]: WARNING:tornado.access:404 GET / (192.168.1.100) 1.91ms

### Expected behavior

Access evok web UI

### Actual behavior

No access

**Comment by kratochvil01** [comment]
We have separated the web application from Evok for security reasons. If you want the web interface , you have to install it using `apt update && apt install evok-web`. More information about Evok web is [here](https://github.com/UniPiTechnology/evok-web-jq).

More information about the changes in the new Evok can be found in the [README](https://github.com/UniPiTechnology/evok/tree/dev-bookworm?tab=readme-ov-file#major-changes-between-evok-v2-and-v3).
