### ISSUE TITLE
HTTP Port of evok-neuron.conf does not work

### ISSUE THREAD

**Issue by martbrugg** [UniPiTechnology/evok#17]
Hi,

when I change the HTTP Port for my Neuron to e.g. Port 81 and restart the Neuron, the Port does not change. I always keeps the port 8088.

**Comment by phillipsnick** [comment]
Had the same issue, looks like you need to define the port against the process. See https://github.com/UniPiTechnology/evok/blob/master/evok/evok.py#L384

For example

`/usr/bin/python /opt/evok/evok.py --path1=/etc/evok.conf --path2=/etc/evok-neuron.conf --port=81`

You can adjust the service to include the port within file `cat /etc/systemd/system/evok.service`
