### ISSUE TITLE
Neuron L203 - AO wrong voltage - 3.3V instead of 10V

### ISSUE THREAD

**Issue by hellpf** [UniPiTechnology/evok#20]
In the last version of the evok (2days ago) I did found a problem with an analog output. If I choose in the GUI 10V (or I'll send it over WS message/http post) there is only 3.3V at the output as the maximum. 10V should be reached only with WS message/http post once I send 30!

`wget -qO- http://10.0.1.122/rest/ao/1_01 --post-data='value=30'`

or 
```
{
            cmd: 'set',
            dev: 'ao',
            unit: 'V',
            circuit: '1_01',
            value: 30
}
```

**Comment by tknot** [comment]
It appears that there was a wrong divider applied to the analog outputs (and only the outputs) on Neuron! It should be fixed in c53c789160e7895ee18de701a1ea6c9bc789933e
