### ISSUE TITLE
Ability to change Neuron input debounce values

### ISSUE THREAD

**Issue by phillipsnick** [UniPiTechnology/evok#22]
Currently these seem to default to 50ms, I'm assuming it's possible to increase/decrease this looking at the source code (https://github.com/UniPiTechnology/evok/blob/master/evok/neuron.py#L359) and the slider in the provided interface (which throws many JS errors) unless this is something with is UniPi v1 specific.

Figured I'd debug this further by manually executing a POST via Postman to `http://IP:8088/rest/input/2_01` 

Which returns 

```
{"errors": {"__all__": "Input instance has no attribute '_regdebounce'"}, "success": false}
```

Altered the following line https://github.com/UniPiTechnology/evok/blob/master/evok/neuron.py#L361
to `if not (self.regdebounce is None):` as theres no reference to _regdebounce inside the class.

Which then gives me

```
{"errors": {"__all__": "'Board' object has no attribute 'write_regs'"}, "success": false}
```

As theres no documentation for the underlying board I'm a little unsure on how I can attempt to resolve this issue myself. Any help on this would be much appreciated :)

**Comment by tknot** [comment]
This should now be fixed, as of 9ff96220993b6bf5cb7af5694dbee6f5c2385d8d
