### ISSUE TITLE
evok error with wget

### ISSUE THREAD

**Issue by EnriqueV** [UniPiTechnology/evok#23]
Hi, i have a unipi with 1Wire 4-Relay + 4-DI extension, but when i send a HTTP POST petition 
i have his error:
![alt text](http://res.cloudinary.com/dcbi3quoh/image/upload/v1495054460/rele_pj51zf.png)
I can only turn on 8 relays
and I can't do it from the GUI

**Comment by tomashora** [comment]
Please make sure the configuration is OK and also paste the addres of the 1Wire 4-Relay + 4-DI extension
https://github.com/UniPiTechnology/evok/blob/master/etc/evok-unipi1.1.conf#L248

**Comment by tknot** [comment]
Considered solved until further feedback
