### ISSUE TITLE
[GENERAL] Websocket cmd:all

### ISSUE THREAD

**Issue by flettieri** [UniPiTechnology/evok#36]
Hi all
the websocket cmd:all is affected by bug. Every time I run it the following exception is raised:
`unsupported operand type(s) for +=: 'dict' and 'list'`
At line 148 
`result = {}`
is initialized as dict but later in line 152 : 
`result += map(lambda dev: dev.full(), Devices.by_int(dev))`
there is a concatenation between dict (result) and list (the result of the fuction dev.full() )
A quick workaround to solve the issue is initialize result as list
`result=[]`

**Comment by tknot** [comment]
Confirmed in the latest master; issue same as https://forum.unipi.technology/topic/431/problem-using-cmd-all-using-websockets - appears to have resurfaced?

**Comment by tknot** [comment]
Thank you for the report! I will fix this within the next public master commit.

**Comment by tknot** [comment]
This should now be fixed again, as of ( d8e4ed7eb04334d5de095e6f084fa8eb1a2ed6fd )

**Comment by tknot** [comment]
Marked as fixed for now
