### ISSUE TITLE
[GENERAL] Prevent immediate automatic restart which causes 100% CPU usage

### ISSUE THREAD

**Issue by tomashora** [UniPiTechnology/evok#43]
Evok starts immediately if it fails to start (eg. a port is used by another process - https://forum.unipi.technology/topic/516/evok-high-cpu-usage/7 ) which causes 100% usage of CPU.

This can be fixed by StartLimitIntervalSec and StartLimitBurst of the systemd script - https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=

**Comment by tknot** [comment]
Should be fixed in the latest commit (0b4a114f242617ce9febc165dfd2ac8a3dafaf91) needs testing to confirm
