### ISSUE TITLE
[NEURON] Not all LED events are not emitted via the WebSocket

### ISSUE THREAD

**Issue by phillipsnick** [UniPiTechnology/evok#44]
### Prerequisites

* [ ] Are you running the latest Master or the latest release version? 

2.0.1

### Description

On the Neuron if you change the LED state via the HTTP control panel, WebSocket events are only emitted for circuit 1.01.

Example toggling 1.01 I will receive:

```
{ value: 0, circuit: '1_01', dev: 'led', glob_dev_id: 1 }
```

```
{ value: 1, circuit: '1_01', dev: 'led', glob_dev_id: 1 }
```

Toggling 1.02, 1.03 or 1.04 no output is received.

**Comment by tknot** [comment]
This should now be fixed by the as-of-now latest commit (c155975e1f4716ac687fb04661bb7ad6521c8978)
