### ISSUE TITLE
[GENERAL] Webhook http rest way to get input changes

### ISSUE THREAD

**Issue by sworteu** [UniPiTechnology/evok#5]
It would be great if one could set a webhook, or another form of feedback without websockets to get input changes.

**Comment by leogaggl** [comment]
I would very much second the webhook option...

**Comment by tknot** [comment]
Webhook implementation now added in latest Master ( 03ea5ad433271d83d39293c578609d91f2d4111b ).

The implementation may however not work across all servers/interfaces, any feedback is welcome.

**Comment by wesleydv** [comment]
The webhook does not provide any data from the triggering event.

I believe the webhook would be much more relevant if the request would carry the data from the triggering event and the values that changed because of it.

**Comment by tknot** [comment]
@wesleydv This will be quite easy to add as an optional mode. We are looking to expand the webhook functionality with filtering anyhow (since as it stands the analog outputs generate far too many events), so this will come in the next release.

**Comment by tknot** [comment]
@wesleydv Please try the webhook implementation in the current public beta ( d8e4ed7eb04334d5de095e6f084fa8eb1a2ed6fd ) on master. There are two new config options which can be used to customize webhook behavior.

**Comment by wesleydv** [comment]
Enabling webhook_complex_events only seems to send an empty post body on sensor updates.
Input changes does not send any request.
webhook_device_mask is set to  ["input", "sensor"]

**Comment by tknot** [comment]
This should be fixed in the release candidate 2.0a (and the last beta as well)
