### ISSUE TITLE
[UNIPI 1.1] RPi-3B+: Installation Issue, tornadows missing

### ISSUE THREAD

**Issue by rudyvan** [UniPiTechnology/evok#53]
Hello,

I tried a fresh install with the latest version of jessie, version 2018-03-13 desktop and the latest RPI 3 B+
I installed evok 2.0, the legacy version and via git clone, but each time the same result.

evok does not start and if tried manually:

```
cd /opt/evok
sudo python evok.py
```

the following error comes up:

```
Traceback (most recent call last):
File "evok.py", line 24, in <module>
from tornadows import soaphandler, webservices
ImportError: No module named tornadows
```

I tried to find how to install __tornadows__, but cannot find help.
I think that tornado is properly installed, also toro.
How to get tornadows?

Any advice?

Kind Regards,
Rudy

**Comment by tknot** [comment]
Will look into it.
tornadows is part of tornado-webservices which can be installed via "pip install tornado-webservices"

**Comment by rudyvan** [comment]
Tried this already, installing tornado-webservices does not solve the issue unfortunately.

**Comment by tknot** [comment]
For now you can use our OSS image from 
https://files.unipi.technology/s/public?path=%2FSoftware%2FOpen-Source%20Images

It's essentially Raspbian Stretch Lite with custom kernel drivers. I'll have a look into it urgently.

**Comment by tknot** [comment]
I have installed the latest Raspbian Stretch Desktop, along with version v2.0.3, using the instructions on GH
- changed both website port and API port, no WiFi
- website appears to work fine, as does EVOK

**Comment by tknot** [comment]
Wait - 3B+? 3B+ is for now only supported in our latest custom image. We do have a testing machine for it, but porting everything will take a little while.

Apologies for the confusion

**Comment by rudyvan** [comment]
Indeed, i was trying with RPI3 B+ the shiny new raspberry.
I have time, not an urgent pressing matter as i can downgrade.

**Comment by tknot** [comment]
We did make the very latest image compatible with the new 3B+, but it was a lot of work, and I'm afraid that we only tested it on Neuron rather UniPi 1.1

**Comment by tknot** [comment]
I can confirm that 3B+ should now work with the v2.0.3a release with UniPi Lite and 1.1. It may be necessary to use a clean image.

**Comment by tknot** [comment]
It seems like you don't have Tornado installed. Really all I've done is to take UniPi 1.1, a fresh Raspbian Desktop image and follow the GitHub instructions. After this I had everything running correctly on localhost.

**Comment by tknot** [comment]
Do the steps you have taken differ in some way? I am honestly at loss.

**Comment by rudyvan** [comment]
my installation program is using a git clone as in 

```
	git clone https://github.com/UniPiTechnology/evok.git
	cd $HOME_DIR/evok
	chmod +x install-evok.sh
	./install-evok.sh
```
i always used this method, could that cause the issue?

**Comment by tknot** [comment]
Possibly. From the errors it looks like the required libraries are not
installed for some reason. The installation script does this via simple
apt-get and pip install, and it's done unconditionally for all
configurations.

**Comment by tknot** [comment]
There shouldn't be a difference between master and the release version in this respect though.

**Comment by rudyvan** [comment]
i executed manually the following script:
```
sudo apt-get update
sudo apt-get install -y python-ow python-pip make python-dev nginx vim
sudo pip install tornado==4.5.3
sudo pip install toro jsonrpclib pymodbus pyyaml tornado_json tornado-webservices pyusb python-dali
sudo pip install pymodbus --upgrade
```
it responded that was already installed or already the newest version, so nothing extra got installed by typing manually.   
result was the same, tornado.httpserver module is missing.
does that not get installed with the above installation script?
I am at a loss too what is wrong.

**Comment by tknot** [comment]
It is a core part of Tornado. When you exectured the commands, did you get
any errors?

**Comment by rudyvan** [comment]
![image](https://user-images.githubusercontent.com/13715940/38353171-f01da506-38b5-11e8-8de4-163cee42838d.png)

no errors, see image.

**Comment by tknot** [comment]
Do you have python 3 installed by any chance? Perhaps it is trying to run it via it instead.

**Comment by rudyvan** [comment]
Found the solution!
I redid the installation manually and prefixed the pip command with python2.7 -m to make sure it installed for python2.7 and then it worked.

for example i did:
```
sudo python2.7 -m pip install jsonrpclib
sudo python2.7 -m install tornado==4.5.3
sudo python2.7 -m pip install toro jsonrpclib pymodbus pyyaml tornado_json tornado-webservices pyusb python-dali

``` 
The reason why i had this issue and not you is possibly because i installed the latest pip version with the commands :
```
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
```
maybe best to update the install files then we are sure that the install happens for version 2.7 and not for some other python version depending on pip?
Thanks for your support!
