### ISSUE TITLE
[GENERAL] webserver port

### ISSUE THREAD

**Issue by rudyvan** [UniPiTechnology/evok#55]
I have been running a reinstall test with the latest evok, RP3 B+ and raspbian image (2018/04/18) and everything worked fine with the exception of the web server port which defaulted to 80 instead of the value 8180 that i had entered during the installation.
I installed with Unipi 1.1 

I corrected nginx/sites-enabled as per the picture below and it worked.
So for me the error is gone and i hope it is fixed when i need to install again.
 
![image](https://user-images.githubusercontent.com/13715940/39082449-9d060138-4553-11e8-9179-f6a874e63b87.png)

I did not run the install again or looked for the issue in the installation script, but just want to mentioned this happened to my install.
Thanks

**Comment by tknot** [comment]
It looks like this got broken in a recent commit, I'll fix it shortly

**Comment by tknot** [comment]
This should be fixed since https://github.com/UniPiTechnology/evok/commit/d762f09d3485ca30b1f2fa5ff57f711bb87f753a

I forgot to update the issue earlier, apologies

**Comment by tknot** [comment]
Considered solved unless further problems arise
