### ISSUE TITLE
Read BCD code on 4 digital inputs

### ISSUE THREAD

**Issue by phlegx** [UniPiTechnology/evok#7]
Hi! 

I have a BCD code as signal on 4 digital inputs. How can I read the code? Evok should send a message (websocket) if on the 4 digital inputs a BCD signal is arrived. Any idea?

**BCD code:** https://en.wikipedia.org/wiki/Binary-coded_decimal

**Comment by tknot** [comment]
BCD is an application concern, not something that should be handled by the internal API. It is quite simple to implement it yourself in JS on your website, see e.g. [https://gist.github.com/joaomaia/3892692](url).

**Comment by tknot** [comment]
Not an issue
