### ISSUE TITLE
Legacy install getting stuck on raspbian

### ISSUE THREAD

**Issue by hennjo** [UniPiTechnology/evok#90]
### Prerequisites

* [No] Are you running the latest Master or the latest release version?
* [Yes ] Did you try to reinstall EVOK?
* [ Yes] Did you perform a cursory search on the [forum] and [google]?

### Log files needed

Include the output of the following commands on your Neuron/UniPi device:

```
sudo su
cat /var/log/evok.access.log
ps -fax
cat /var/log/evok.log
```
`pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# cat /var/log/evok.access.log
cat: /var/log/evok.access.log: No such file or directory
root@raspberrypi:/home/pi# ps -fax
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    3 ?        I<     0:00  \_ [rcu_gp]
    4 ?        I<     0:00  \_ [rcu_par_gp]
    5 ?        I      0:00  \_ [kworker/0:0-events]
    7 ?        I      0:00  \_ [kworker/u8:0-events_unbound]
    8 ?        I<     0:00  \_ [mm_percpu_wq]
    9 ?        S      0:00  \_ [ksoftirqd/0]
   10 ?        I      0:00  \_ [rcu_sched]
   11 ?        S      0:00  \_ [migration/0]
   12 ?        S      0:00  \_ [cpuhp/0]
   13 ?        S      0:00  \_ [cpuhp/1]
   14 ?        S      0:00  \_ [migration/1]
   15 ?        S      0:00  \_ [ksoftirqd/1]
   17 ?        I<     0:00  \_ [kworker/1:0H-kblockd]
   18 ?        S      0:00  \_ [cpuhp/2]
   19 ?        S      0:00  \_ [migration/2]
   20 ?        S      0:00  \_ [ksoftirqd/2]
   23 ?        S      0:00  \_ [cpuhp/3]
   24 ?        S      0:00  \_ [migration/3]
   25 ?        S      0:00  \_ [ksoftirqd/3]
   27 ?        I<     0:00  \_ [kworker/3:0H-kblockd]
   28 ?        S      0:00  \_ [kdevtmpfs]
   29 ?        I<     0:00  \_ [netns]
   30 ?        I      0:00  \_ [kworker/0:1-mm_percpu_wq]
   31 ?        I      0:00  \_ [kworker/1:1-events]
   32 ?        S      0:00  \_ [kauditd]
   33 ?        S      0:00  \_ [khungtaskd]
   34 ?        S      0:00  \_ [oom_reaper]
   35 ?        I<     0:00  \_ [writeback]
   36 ?        S      0:00  \_ [kcompactd0]
   54 ?        I<     0:00  \_ [kblockd]
   55 ?        I<     0:00  \_ [blkcg_punt_bio]
   56 ?        S      0:00  \_ [watchdogd]
   57 ?        I      0:00  \_ [kworker/2:1-events]
   59 ?        I<     0:00  \_ [rpciod]
   60 ?        I<     0:00  \_ [kworker/u9:0-hci0]
   61 ?        I<     0:00  \_ [xprtiod]
   62 ?        S      0:00  \_ [kswapd0]
   63 ?        I<     0:00  \_ [nfsiod]
   64 ?        I<     0:00  \_ [iscsi_eh]
   65 ?        I<     0:00  \_ [dwc_otg]
   66 ?        I<     0:00  \_ [DWC Notificatio]
   67 ?        I      0:00  \_ [kworker/1:2-events]
   68 ?        S<     0:01  \_ [vchiq-slot/0]
   69 ?        S<     0:00  \_ [vchiq-recy/0]
   70 ?        S<     0:00  \_ [vchiq-sync/0]
   71 ?        S      0:00  \_ [vchiq-keep/0]
   72 ?        S<     0:00  \_ [SMIO]
   73 ?        I      0:00  \_ [kworker/1:3-events]
   74 ?        I<     0:00  \_ [mmc_complete]
   76 ?        I<     0:00  \_ [kworker/0:1H-mmc_complete]
   77 ?        S      0:00  \_ [jbd2/mmcblk0p2-]
   78 ?        I<     0:00  \_ [ext4-rsv-conver]
   79 ?        I<     0:00  \_ [kworker/2:1H-kblockd]
   80 ?        I<     0:00  \_ [kworker/0:2H-kblockd]
   81 ?        I<     0:00  \_ [ipv6_addrconf]
   83 ?        I      0:00  \_ [kworker/u8:1-events_unbound]
   94 ?        I<     0:00  \_ [kworker/3:2H-kblockd]
  100 ?        I<     0:00  \_ [kworker/1:2H-kblockd]
  105 ?        I<     0:00  \_ [kworker/2:2H-kblockd]
  174 ?        S<     0:00  \_ [SMIO]
  184 ?        I<     0:00  \_ [mmal-vchiq]
  191 ?        I<     0:00  \_ [mmal-vchiq]
  193 ?        I<     0:00  \_ [mmal-vchiq]
  194 ?        I<     0:00  \_ [mmal-vchiq]
  240 ?        I<     0:00  \_ [cfg80211]
  248 ?        I<     0:00  \_ [brcmf_wq/mmc1:0]
  250 ?        S      0:00  \_ [brcmf_wdog/mmc1]
  466 ?        I      0:00  \_ [kworker/3:3-mm_percpu_wq]
  468 ?        I      0:00  \_ [kworker/3:4-events_power_efficient]
  500 ?        I<     0:00  \_ [kworker/u9:2-hci0]
  650 ?        I      0:00  \_ [kworker/2:3-cgroup_destroy]
  871 ?        S<     0:00  \_ [krfcommd]
 1255 ?        I<     0:00  \_ [kworker/1:1H]
 1280 ?        I      0:00  \_ [kworker/0:2-events]
 1290 ?        I      0:00  \_ [kworker/3:0-events_power_efficient]
 1363 ?        I      0:00  \_ [kworker/1:0-events]
 1389 ?        I<     0:00  \_ [kworker/0:0H]
 1451 ?        I      0:00  \_ [kworker/0:3-events]
    1 ?        Ss     0:08 /sbin/init splash
  108 ?        Ss     0:00 /lib/systemd/systemd-journald
  144 ?        Ss     0:01 /lib/systemd/systemd-udevd
  299 ?        Ssl    0:00 /lib/systemd/systemd-timesyncd
  343 ?        Ssl    0:00 /usr/sbin/rsyslogd -n -iNONE
  345 ?        SNs    0:00 /usr/sbin/alsactl -E HOME=/run/alsa -s -n 19 -c rdaemon
  347 ?        Ss     0:00 /usr/sbin/cupsd -l
  657 ?        S      0:00  \_ /usr/lib/cups/notifier/dbus dbus://
  351 ?        Ss     0:00 /usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --socket /run/thd.socket --user nobody --deviceglob /dev/input/event*
  357 ?        Ssl    0:00 /usr/lib/udisks2/udisksd
  363 ?        SLsl   0:00 /usr/sbin/rngd -r /dev/hwrng
  379 ?        Ss     0:00 /usr/sbin/cron -f
  389 ?        Ss     0:01 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  402 ?        Ss     0:00 avahi-daemon: running [raspberrypi.local]
  431 ?        S      0:00  \_ avahi-daemon: chroot helper
  403 ?        Ss     0:00 /lib/systemd/systemd-logind
  405 ?        Ss     0:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
  426 ?        Ss     0:00 /sbin/dhcpcd -q -b
  483 ?        Ss     0:00 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -Dnl80211,wext
  499 ?        S      0:00 /usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow - b8:27:eb:e4:8b:e2
  518 ?        Ssl    0:00 /usr/lib/policykit-1/polkitd --no-debug
  520 ?        Ssl    0:00 /usr/sbin/cups-browsed
  524 ?        Ss     0:00 /usr/lib/bluetooth/bluetoothd
  559 ?        Ssl    0:00 /usr/sbin/lightdm
  630 tty7     Ssl+   0:00  \_ /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
  672 ?        Sl     0:00  \_ lightdm --session-child 13 16
  691 ?        Ssl    0:00      \_ /usr/bin/lxsession -s LXDE-pi -e LXDE
  732 ?        Ss     0:00          \_ /usr/bin/ssh-agent x-session-manager
  782 ?        S      0:00          \_ openbox --config-file /home/pi/.config/openbox/lxde-pi-rc.xml
  785 ?        Sl     0:00          \_ lxpolkit
  787 ?        Sl     0:02          \_ lxpanel --profile LXDE-pi
  788 ?        Sl     0:01          \_ pcmanfm --desktop --profile LXDE-pi
  619 ?        Ss     0:00 /usr/sbin/sshd -D
 1074 ?        Ss     0:00  \_ sshd: pi [priv]
 1080 ?        S      0:00  |   \_ sshd: pi@pts/0
 1081 pts/0    Ss     0:00  |       \_ -bash
 1145 pts/0    S      0:00  |           \_ sudo su
 1146 pts/0    S      0:00  |               \_ su
 1147 pts/0    S      0:00  |                   \_ bash
 1175 pts/0    S+     0:00  |                       \_ bash install-evok.sh
 1182 pts/0    S+     0:00  |                           \_ grep -q include config_unipi.inc
 1330 ?        Ss     0:00  \_ sshd: pi [priv]
 1348 ?        S      0:00      \_ sshd: pi@pts/1
 1349 pts/1    Ss     0:00          \_ -bash
 1464 pts/1    S      0:00              \_ sudo su
 1465 pts/1    S      0:00                  \_ su
 1466 pts/1    S      0:00                      \_ bash
 1480 pts/1    R+     0:00                          \_ ps -fax
  632 tty1     Ss     0:00 /bin/login -f
  745 tty1     S+     0:00  \_ -bash
  668 ?        Ssl    0:00 /usr/lib/colord/colord
  680 ?        Ss     0:00 /lib/systemd/systemd --user
  681 ?        S      0:00  \_ (sd-pam)
  699 ?        Ss     0:00  \_ /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  749 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfsd
  910 ?        Sl     0:00  |   \_ /usr/lib/gvfs/gvfsd-trash --spawner :1.4 /org/gtk/gvfs/exec_spaw/0
  767 ?        Sl     0:00  \_ /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
  820 ?        S<sl   0:05  \_ /usr/bin/pulseaudio --daemonize=no
  846 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfs-udisks2-volume-monitor
  850 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfs-mtp-volume-monitor
  854 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
  858 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfs-goa-volume-monitor
  863 ?        Ssl    0:00  \_ /usr/lib/gvfs/gvfs-afc-volume-monitor
  794 ?        Ss     0:00 /usr/bin/ssh-agent -s
  796 ?        S      0:00 sudo -AE piwiz
  817 ?        S      0:00  \_ piwiz
  806 ?        S      0:00 sh /etc/xdg/lxsession/LXDE-pi/sshpwd.sh
  812 ?        Sl     0:02  \_ zenity --warning --width=400 --text=SSH is enabled and the default password for the 'pi' user has not been changed.\n\nThis i
  815 ?        S      0:01 /usr/bin/python3 /usr/share/system-config-printer/applet.py
  842 ?        SNsl   0:00 /usr/lib/rtkit/rtkit-daemon
  876 ?        Sl     0:00 /usr/lib/menu-cache/menu-cached /run/user/1000/menu-cached-:0
 1032 ?        Ss     0:00 /lib/systemd/systemd-timedated
root@raspberrypi:/home/pi# cat /var/log/evok.log
cat: /var/log/evok.log: No such file or directory
`

### Description

Legacy installation stuck at the following after a few seconds.

`root@raspberrypi:/home/pi# cd evok-2.3.6/
root@raspberrypi:/home/pi/evok-2.3.6# bash install-evok.sh
########################
########################
####################################
####################################
^[OA^[OB^C
root@raspberrypi:/home/pi/evok-2.3.6# su pi
pi@raspberrypi:~/evok-2.3.6 $ sudo bash install-evok.sh 
########################
########################
####################################
####################################
`

### Steps to Reproduce

1. Install a fresh raspbian using a RPI3B+
2. Follow legacy installation instructions from README.md
3. get stuck :)

**Expected behavior:** I'd expect the installer to go through or a process that's doing some work.

**Actual behavior:** Output as above. If you change the command to sudo bash -x install-evok.sh you'll see that you get stuck on 

> + echo '####################################'
> ####################################
> + echo '## Using kernel newer than 3.18.5 ##'
> ## Using kernel newer than 3.18.5 ##
> + echo '####################################'
> ####################################
> + INCLUDE_LINE='include config_unipi.inc'
> + grep -q 'include config_unipi.inc'
> 

After changing that line to 
> if ! grep -f "$INCLUDE_LINE"; then
 the script ran succesfully.

[forum]:https://forum.unipi.technology/category/4/official-evok-api
[google]:http://www.google.com/

**Comment by kratochvil01** [comment]
Hello, you can try [beta evok](https://github.com/UniPiTechnology/evok/tree/dev-bookworm).

**Comment by kratochvil01** [comment]
Evok v3.0.1 is released.
