### ISSUE TITLE
Webhook calls with json body sent with content-type 'application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by steinmaerivoet** [UniPiTechnology/evok#91]
### Prerequisites

* [ ] Are you running the latest Master or the latest release version?
* [ ] Did you try to reinstall EVOK?
* [ ] Did you perform a cursory search on the [forum] and [google]?

### Log files needed

Include the output of the following commands on your Neuron/UniPi device:

```
sudo su
cat /var/log/evok.access.log
ps -fax
cat /var/log/evok.log
```

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

[forum]:https://forum.unipi.technology/category/4/official-evok-api
[google]:http://www.google.com/

**Comment by kratochvil01** [comment]
Solved in Evok v3.0.1 release.
