### ISSUE TITLE
EVOK and xS11 problem in save configuration

### ISSUE THREAD

**Issue by kratas** [UniPiTechnology/evok#97]
### Prerequisites

* [ yes] Are you running the latest Master or the latest release version?
* [ yes] Did you try to reinstall EVOK?
* [yes ] Did you perform a cursory search on the [forum] and [google]?

unipi Patron M207 and expansion module xS11, in evok.conf I set the expansion module, in evok I see it, inputs and outputs, relay control works.
But I need to set a direct switch on the inputs for the expansion module, as well as for the M207, but unfortunately it always ends with an error message.

`Operation failed with the following error: yielded unknown object <modbusclient_rs485.AsyncFifoTransactionManager object at 0xffffbbb58e50>`

The input / output name is saved despite the error message, unfortunately not the setting and that is crucial for me.

**Comment by kratochvil01** [comment]
Solved in Evok v3.0.1
