### ISSUE TITLE
can not install evok on fresh install of raspberry os or rassbian buster

### ISSUE THREAD

**Issue by lukasx102** [UniPiTechnology/evok#99]
[Description of the bug or feature]
Hello,

please can you confirm that evok is possible on fresh installation of Raspberry OS?

I faced with a lot of issues during installation 
Problem with certificate ?

ERROR: The certificate of ‘repo.unipi.technology’ is not trusted.
ERROR: The certificate of ‘repo.unipi.technology’ has expired.
gpg: no valid OpenPGP data found.
root@raspberrypi:/home/pi# 
root@raspberrypi:/home/pi# apt-get install evok
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:2
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:2
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:3
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/unipi.list:1 and /etc/apt/sources.list.d/unipi.list:3
E: Unable to locate package evok

I do not want to use unipi node red image, because I can not configure there hidden wifi..

please help me
thanks

**Comment by qcraftd** [comment]
64 bit ?

**Comment by kratochvil01** [comment]
Evok v3.0.1 is released. (for debian bookworm)
